// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eicwicmitvrkjwwyujhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpY3dpY21pdHZya2p3d3l1amhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODA1NDksImV4cCI6MjA2NTk1NjU0OX0._7jDlBKjwqE63_E24d0vYDc_Yem92e5fR4v9EAok700";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);